In [61]:
# Library Imports

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime

# NOTE!!! CODE REQUIRED TO RECIEVE INPUT VARIABLES  s_date, e_date

# TEST
s_date = '2019-04-19'
e_date = '2019-05-19'

# Datetime allocation
s_date = datetime.strptime(s_date, "%Y-%m-%d") # INPUT MUST BE IN THIS FORMAT
e_date = datetime.strptime(e_date, "%Y-%m-%d")

In [62]:
# Load Data
calendar_df = pd.read_csv("Data/calendar_dec18.csv")

# Datframe Convertions

#date to datetime datatype
calendar_df['date'] = pd.to_datetime(calendar_df['date'])

#listing_id to id in calendar_df
calendar_df.rename(columns={'listing_id': 'id'}, inplace=True)

In [63]:
# Filtering by dates
def date_filtered_listings(calendar_df,s_date, e_date):
    fprice_df = calendar_df[((calendar_df['date'] > s_date) & (calendar_df['date'] < e_date))]
    return fprice_df
    # Outputs data frame containing filtered listings

In [64]:
# Execute functions
fprice_df = date_filtered_listings(calendar_df,s_date, e_date)
fprice_df

                id       date available    price
92           12351 2019-05-18         t  $103.00
93           12351 2019-05-17         t  $103.00
94           12351 2019-05-16         t  $103.00
95           12351 2019-05-15         t  $103.00
96           12351 2019-05-14         t  $103.00
...            ...        ...       ...      ...
13381028  30540048 2019-04-24         f      NaN
13381029  30540048 2019-04-23         f      NaN
13381030  30540048 2019-04-22         f      NaN
13381031  30540048 2019-04-21         f      NaN
13381032  30540048 2019-04-20         f      NaN

[1063169 rows x 4 columns]

In [65]:
# Drop Unneed Attributes
fprice_df = fprice_df.drop('available', axis=1)
fprice_df = fprice_df.reset_index(drop=True)
fprice_df

               id       date    price
0           12351 2019-05-18  $103.00
1           12351 2019-05-17  $103.00
2           12351 2019-05-16  $103.00
3           12351 2019-05-15  $103.00
4           12351 2019-05-14  $103.00
...           ...        ...      ...
1063164  30540048 2019-04-24      NaN
1063165  30540048 2019-04-23      NaN
1063166  30540048 2019-04-22      NaN
1063167  30540048 2019-04-21      NaN
1063168  30540048 2019-04-20      NaN

[1063169 rows x 3 columns]

In [66]:
# Remove rows where 'price' is NaN
fprice_df = fprice_df.dropna(subset=['price'])

# Convert price datatype to float
fprice_df['price'] = fprice_df['price'].replace('[\$,]', '', regex=True).astype(float)

C:\Users\zhard\AppData\Local\Temp\ipykernel_30968\3352988718.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fprice_df['price'] = fprice_df['price'].replace('[\$,]', '', regex=True).astype(float)

               id       date  price
0           12351 2019-05-18  103.0
1           12351 2019-05-17  103.0
2           12351 2019-05-16  103.0
3           12351 2019-05-15  103.0
4           12351 2019-05-14  103.0
...           ...        ...    ...
1062810  29841374 2019-05-16   80.0
1062811  29841374 2019-05-15   80.0
1062812  29841374 2019-05-14   80.0
1062813  29841374 2019-05-13   80.0
1062814  29841374 2019-05-12   80.0

[330776 rows x 3 columns]

In [67]:
#Getting Min, Max price values
min_price = fprice_df["price"].min()
max_price = fprice_df["price"].max()

14.0
11456.0

In [72]:
# Loop unique id and plot
for u_id in fprice_df['id'].unique():
    subset = fprice_df[fprice_df['id'] == u_id]
    plt.plot(subset['date'], subset['price'], label=f'ID: {unique_id}')

# Titles and labels
plt.title(f'Property Price distribution, {s_date} - {e_date}')
plt.xlabel('Date')
plt.ylabel('Price')

# Formatting dates
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
plt.gca().xaxis.set_major_locator(mdates.MonthLocator())
plt.gcf().autofmt_xdate()

# Add a legend
plt.legend(loc='upper left', bbox_to_anchor=(1, 1))

# Layout Adjustment
plt.tight_layout()

# Show the plot
plt.show()

C:\Users\zhard\AppData\Local\Temp\ipykernel_30968\1163124806.py:20: UserWarning: Tight layout not applied. The bottom and top margins cannot be made large enough to accommodate all axes decorations.
  plt.tight_layout()

ValueError: Image size of 741x261940 pixels is too large. It must be less than 2^16 in each direction.