In [69]:
# Library Imports

import pandas as pd 

# NOTE!!! CODE REQUIRED TO RECIEVE INPUT VARIABLES  sub, s_date, e_date

# TEST
sub = 'Mosman'
s_date = '19/01/2019'
e_date = '19/02/2019'

In [56]:
listings_df = pd.read_csv("Data/listings_summary_dec18.csv")
calendar_df = pd.read_csv("Data/calendar_dec18.csv")

# Datframe Convertions

#date to datetime datatype
calendar_df['date'] = pd.to_datetime(calendar_df['date'])

#listing_id to id in calendar_df
calendar_df.rename(columns={'listing_id': 'id'}, inplace=True)

In [57]:
# Define Functions for Filtered Dataframe Creation

# Filtering by suburb
def suburb_filtered_listings(listings_df, sub):
    fsub_df = listings_df[listings_df['neighbourhood'].str.lower() == sub.lower()]
    return fsub_df
    # Outputs data frame containing filtered listings 

# Filtering by dates
def date_filtered_listings(calendar_df,s_date, e_date):
    fdate_df = calendar_df[((calendar_df['date'] > s_date) & (calendar_df['date'] < e_date))]
    return fdate_df
    # Outputs data frame containing filtered listings

In [70]:
# Execute functions
fsub_df = suburb_filtered_listings(listings_df, sub)
fdate_df = date_filtered_listings(calendar_df,s_date, e_date)

In [72]:
fsub_df = fsub_df.drop_duplicates(subset='id')
fdate_df = fdate_df.drop_duplicates(subset='id')


# Merges both filtered dataframes based on listing id
f_df = pd.merge (fsub_df, fdate_df, on='id')

f_df

#Attribute filtering

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price_x,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date,available,price_y
0,58506,"Studio Yindi @ Mosman, Sydney",279955,John,NaN,Mosman,-33.819268,151.236525,Entire home/apt,140,2,229,2018-12-06,2.37,1,187,2019-02-18,t,$140.00
1,365953,En suite room in gorgeous house!,1827246,Jen,NaN,Mosman,-33.823291,151.236787,Private room,145,5,6,2017-01-14,0.19,1,348,2019-02-18,t,$145.00
2,752978,Balmoral Beach Cottage with Garden,3645455,Tracey,NaN,Mosman,-33.827146,151.249054,Entire home/apt,651,5,4,2014-12-28,0.06,2,349,2019-02-18,t,$650.00
3,771147,Apartment with Water Views,4068265,Daniela,NaN,Mosman,-33.816360,151.243700,Private room,80,1,2,2018-02-25,0.04,1,364,2019-02-18,t,$80.00
4,775552,Balmoral beach Garden Oasis Mosman,2650727,Robbie,NaN,Mosman,-33.826452,151.247865,Entire home/apt,190,3,134,2018-12-02,1.85,1,290,2019-02-18,f,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
529,30537725,Family Friendly Mosman Apartment,18361336,Alex,NaN,Mosman,-33.833973,151.239922,Entire home/apt,155,7,0,NaN,NaN,2,50,2019-02-18,f,NaN
530,30540082,Spacious and cozy 1 bedroom apartment,208642174,Alice,NaN,Mosman,-33.816892,151.245273,Entire home/apt,120,2,0,NaN,NaN,1,147,2019-02-18,f,NaN
531,30563539,CONVENIENT - Heart of Mosman 2BR Apartment,47158011,Jess,NaN,Mosman,-33.833791,151.230242,Entire home/apt,251,2,0,NaN,NaN,1,42,2019-02-18,f,NaN
532,30570831,PROS - Mosman Harmony Executive Escape,16357713,PropertyProviders,NaN,Mosman,-33.820501,151.240867,Entire home/apt,468,7,0,NaN,NaN,103,83,2019-02-18,f,NaN
533,30571665,PROS - The Beehive in Central Mosman,16357713,PropertyProviders,NaN,Mosman,-33.829081,151.241176,Entire home/apt,770,7,0,NaN,NaN,103,34,2019-02-18,f,NaN